### ISSUE TITLE
Resultatdownload

### ISSUE THREAD

**Issue by MarieRathckeLillemark** [davidkonrad/dnaliv2#31]
Fejl i resultatdownload (søg)
•	Oversættelse af presence-absence: 
o	Absence overskriver presence?
o	Ikke alle 2xpresence (pålidelig=1) fremgår af af download
•	Ved søgning indsamlingsperiode 
o	tidlig 2013 slut 2017 giver et andet resultat end ved kun specifikation af tidlig 2013 (dvs uden slutdato)

**Comment by davidkonrad** [comment]
Hvad skal absent  / presence hedde ...? Fundet / Ej fundet ..?

**Comment by MarieRathckeLillemark** [comment]
o	Absence overskriver presence?
Ser ud til at være fint!
o	Ikke alle 2xpresence (pålidelig=1) fremgår af af download
… Jeg er ikke helt sikker her. Der er ingen duplikater af resultaterne, det er kun overall resultater, de samme som vises på kortet under hvert punkt dvs er arten fundet eller ej (Ct-værdierne er i øvrigt heller ikke med).
