### ISSUE TITLE
Dato sortering

### ISSUE THREAD

**Issue by MarieRathckeLillemark** [davidkonrad/dnaliv2#32]
Forkert sortering på dato, blandt andet under analysedato

**Comment by davidkonrad** [comment]
Kunne kun se det gjaldt netop analysedatoer (?) Skyldtes at analysedatoerne på et tidspunkt blev akkumulerede, dvs kan være en liste af flere datoer.

**Comment by MarieRathckeLillemark** [comment]
Ahh, ok, så er der noget at gøre?

**Comment by davidkonrad** [comment]
Ja, lave en særlig sorterings "algoritme" til disse datoer. Har rettet det, har lavet det sådan at i tilfælde er flere datoer sorteres den efter _første_ analysedato.
