### ISSUE TITLE
Admin: til/fra arter og nye arter

### ISSUE THREAD

**Issue by MarieRathckeLillemark** [davidkonrad/dnaliv2#34]
Der er lidt bøvl med koblingen mellem artslisten og resultater. Der er ”lag tid” fra at man klikker en art til, til den fremkommer under resultater (som mulig at tilføje). Jeg var faktisk nød til at lukke siden ned og åbne den igen.

Når så fx man har slået skrubtudse og butsnudet frø til fremkommer de KUN i nye resultater, og ikke gamle. Det er måske nok også fint nok i og med at de nye arter jo vil analyseres på et andet tidspunkt…

Derudover kan man ikke tilføje nye arter. Måske er der sket noget med koblingen mellem allearter og datasystemet (nyt link måske..?). Jeg ville tilføje Latterfrø og Kortbenet grøn frø…

**Comment by davidkonrad** [comment]
1. Netop!. Ændrede alle arter API'et til https i starten af november (ifb bioblitz) DNA & Liv kørte http op imod API'et så forbindelsen fejlede. 

2. For at føje en art (også en nyoprettet art) til et eksisterende resultatsæt skal du vælge "tilføj ny art" /  "gentilføj art" nederst i resultat vinduet. Alle tilvalgte taxons ligger som id-referencer på hver enkelt resultatsæt, det bliver simpelthen noget megarod hvis systemet skal ned og tilføje en art til 277 eksisterende resultatsæt (eller fjerne dem).  Den oprindelige ide var også at holde mængden af tomme eller døde artsreferencer på hver enkelt resultatsæt nede på et minimum.

3. Ja, listen af arter / taxoner blev ikke opdateret "globalt", når man havde ændret i listen. Har rettet dette også.

4. "Kortbenet grøn frø" findes ikke i allearter-databasen. Jeg har ændret det sådan, at hvis man skriver i feltet, dvs ikke nødvendigvis laver et opslag, og har udfyldt både Latinsk navn og dansk navn (f.eks bare et x) så kan arten oprettes med artsgruppenavn "Ukendt" (det kan så senere rettes i listen nedenunder)
